name: Sync Documentation to Wiki

on:
  push:
    branches:
      - main

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and clean wiki directory
        run: |
          if [ -d "wiki" ]; then
            rm -rf wiki
          fi

      - name: Clone wiki repository
        run: git clone "https://github.com/mayukhg/AIAgentTravelPlanner.wiki.git" wiki

      - name: Setup Git User
        run: |
          git config --global user.name "mayukhg"
          git config --global user.email "mayukhg@gmail.com"
        
      - name: Update wiki documentation
        run: |
          cp -r docs/* wiki/
          cd wiki
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Update wiki documentation from docs/ folder"
            # This command pushes the current commit to the remote 'master' branch
            git push origin HEAD:master
          else
            echo "No changes to commit"
          fi
